### ISSUE TITLE
Broaden scope of supported pipelines

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/experimental#39]
See https://github.com/tektoncd/dashboard/issues/47 - this issue and dashboard 47 are very closely linked, and are probably duplicates. 

Webhooks creation and manual pipeline run initiation are much too hardcoded for a small subset of test pipelines. We need a much more flexible design in both areas. Ideally:
- replace our 'sink' code with the EventBinding/TektonListener experimental engine
- See https://github.com/tektoncd/experimental/issues/19 - specifically @ncskier's proposed
```
apiVersion: tekton.dev/v1alpha1
kind: TemplateBinding
metadata:
  name: simple-pipeline-push
  namespace: default
spec:
  templateRef:
    name: simple-pipeline-template
  serviceAccount: default
  event:
    class: cloudevent
    type: com.github.push
  params:
    - name: gitrevision
      value: ${event.head_commit.id}
    - name: gitrepositoryurl
      value: ${event.repository.url}
    - name: dockerusername
      value: ncskier
    - name: dockerappname
      value: helloworldapp
```
This TemplateBinding format gives us a way of defining the parameters that we should attempt to automatically fill in - gitrevision, gitrepositoryurl, and those params that the user must provide - docker username, application name.

We should make every effort to move the Tekton EventBinding integration work forward as a pre-req to this work.
