### ISSUE TITLE
Extend EventListener Route to support self-signed HTTPS 

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/experimental#399]
As a developer I want to set up a webhook from GitHub to the Dashboard webhooks extension EventListener that uses an https:// URL. I want to do this on both OpenShift under this issue. 

Extend the webhooks-extension deployment with two global flags:
1. The first, 'Use https for webhooks' would cause all webhooks to be created with https:// prefixes. This should be set to 'true' by default on OpenShift. 
2. A second global flag should cause all webhooks created in GitHub to have the 'Enable SSL verification' option deselected (see https://developer.github.com/enterprise/2.17/webhooks/creating/#ssl-verification) . SSL verification should be 'on' by default. 

Additionally, update the Route that webhooks are directed to so that http is automatically upgraded to https.

**Comment by akihikokuroda** [comment]
What is the global flag?
  The webhook URL including the protocol is an environment variable in the deployment now.  It can be updated by the user before install.  The InstallxxxBuild.md has install command examples with the sed command embedded to replace the address part of the URL.  
Is this issue updating the example command to include the replacing the protocol part of the URL?

**Comment by mnuttall** [comment]
If setting WEBHOOK_CALLBACK_URL to https: in https://github.com/tektoncd/experimental/blob/master/webhooks-extension/base/300-extension-deployment.yaml always works then we will only need a single variable.

**Comment by mnuttall** [comment]
Aki's all ready pointed out the SSL_VERIFICATION_ENABLED flag - this might meet all our needs!

**Comment by mnuttall** [comment]
So in short, test on 
- OpenShift
- docker desktop
At least with SSL_VERIFICATION_ENABLED=false to ensure that self-signed certificates work correctly. The OpenShift Route will need to support https - is there an easy way to connect setting this, with the setting on the Deployment?

**Comment by akihikokuroda** [comment]
I tested following: 
1. SSL_VERIFICATION_ENABLED=false sets the "SSL verification" "Disable" correctly
2. Setting url with "https" protocol in WEBHOOK_CALLBACK_URL, SSL_VERIFICATION_ENABLED=false works with the webhook ingress with self-signed certificate set in docker desktop.

**Comment by akihikokuroda** [comment]
The route created by the webhook extension doesn't accept https request.  The route 
doesn't have 
```
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
```
after adding these lines.  It worked with the TLS verification disabled.
```
spec:
  host: >-
    el-tekton-webhooks-eventlistener-tekton-pipelines.apps.barbed.os.fyre.ibm.com
  subdomain: ''
  to:
    kind: Service
    name: el-tekton-webhooks-eventlistener
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
```
