### ISSUE TITLE
Validation for pull request event failing for action "closed" from GHE

### ISSUE THREAD

**Issue by brianxjx** [tektoncd/experimental#451]
WebHooks extension

# Expected Behavior
event should be forwarded thru triggers flow.

# Actual Behavior
event is dropped

# Steps to Reproduce the Problem

1. Create webhook
2. Use browser make simple edit
3. Choose to create pull request
4. After monitor task completes, merge PR
5. Observe validation failure in eventlistener logs for action "closed"

# Additional Info

**Comment by brianxjx** [comment]
https://github.com/tektoncd/experimental/pull/354/files#
webhooks-extension/pkg/endpoints/webhook.go

	actions = pipelinesv1alpha1.Param{Name: "Wext-Incoming-Actions", Value: pipelinesv1alpha1.ArrayOrString{Type: pipelinesv1alpha1.ParamTypeString, StringVal: "opened,reopened,synchronize"}}

**Comment by brianxjx** [comment]
I'm trying to make deployment task conditional on the merge&close  git event.  I chose my criteria from
https://developer.github.com/enterprise/2.17/v3/activity/events/types/#pullrequestevent
To that end i coded a condition using some additional params.  Specifically pulling additional fields from the pull_request event.

**Comment by brianxjx** [comment]
Are the acceptable values configurable in the eventlistener document?

**Comment by akihikokuroda** [comment]
No, it is not.

**Comment by akihikokuroda** [comment]
This is working as designed for the webhook extensions.  It is trigger the build when the code is changed and the "close" action doesn't change the code even if the "merge " is true.  We may need to come up idea to handle this case as a new feature.

**Comment by brianxjx** [comment]
So a deployment condition like this can't be done.

Pipelines do more than build so I'm disappointed by your response....

**Comment by akihikokuroda** [comment]
I probably can create a yaml file for the kubectl patch command to enable the "close" action.  That must be used after the webhook is created.

**Comment by akihikokuroda** [comment]
The webhook extension creates the In the eventlistener resource.  It has following section. 
```
    - binding:
        apiversion: v1alpha1
        name: buildah-pipeline-pullrequest-binding
      interceptor:
        header:
        - name: Wext-Trigger-Name
          value: sample-tekton-pipelines-pullrequest-event
        - name: Wext-Repository-Url
          value: https://github.ibm.com/akuroda/simple
        - name: Wext-Incoming-Event
          value: pull_request
        - name: Wext-Secret-Name
          value: ghetoken
        - name: Wext-Incoming-Actions
          value: opened,reopened,synchronize

```
The patch command must add the "close" to the last line above.
The patch command is a little bit tricky .  I hope I can write a yaml file for it.
