### ISSUE TITLE
Tekton beta support (potential issue - getting pipelines still uses v1alpha1)

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/experimental#502]
I noticed this while working https://github.com/tektoncd/experimental/issues/493:

```
export function getPipelines(namespace) {
  const uri = `${dashboardAPIRoot}/proxy/apis/tekton.dev/v1alpha1/namespaces/${namespace}/pipelines`;
  return get(uri);
}
```

in src/api/index.js, should be v1beta1. Implication here is likely that the user won't be able to select pipelines, and we didn't notice this with our test resources are still v1alpha1, see https://github.com/pipeline-hotel/example-pipelines/blob/master/triggers-resources/config/github/simple-pipeline/simple-pipeline.yaml which at the time of this issue contains

```
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  params:
  - name: event-type
    type: string
    description: "The event type"
  resources: 
  - name: git-source
    type: git
  - name: docker-image
    type: image
  tasks:
```
