### ISSUE TITLE
Add ability to parse variables in expression from context for CEL

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/experimental#716]
### Feature request

The CEL is a great feature, we plan to adopt in our project, but seems it can not support parse expression which include other variables, for example:
```
  params:
    - name: name
      value: "'hello'"
    - name: types
      value: "type(name)"
```
see the `name` has been defined in first `param` and expect to used in second `param`. 
I guess this is not required in `when express`, but useful in other scenario.

In our case, we will set some initialize variables in some runtime storage (maybe a runtime created CM), and in expression, we will use these variables.
