### ISSUE TITLE
[pipelines-in-pipelines] Add a demo about using results between pipelines

### ISSUE THREAD

**Issue by Letty5411** [tektoncd/experimental#864]
It would be better to add a demo about using `results` between pipelines.
Maybe sth like this:

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-world
spec:
  results:
    - name: message
      value: $(tasks.generate-hello-world.results.message)
  tasks:
    - name: generate-hello-world
      taskSpec:
        results:
          - name: message
        steps:
          - name: generate-message
            image: ubuntu
            script: |
              echo -n "Hello World!" > $(results.message.path)
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: good-morning-good-afternoon
spec:
  params:
    - name: a
      type: string
  tasks:
    - name: echo-good-morning
      params:
        - name: a
          value: "$(params.a)"
      taskSpec:
        params:
          - name: a
        steps:
          - name: echo
            image: ubuntu
            script: |
              #!/usr/bin/env bash
              echo "Good Morning!"
              echo $(params.a)
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pr-2
spec:
  serviceAccountName: 'default'
  pipelineSpec:
    tasks:
      - name: hello
        taskSpec:
          results:
            - name: message
          steps:
            - name: generate-message
              image: reg.docker.alibaba-inc.com/alibase/alios7u2-min:latest
              script: |
                echo -n "Hello World!" > $(results.message.path)
      - name: greeting-results
        taskRef:
          apiVersion: tekton.dev/v1beta1
          kind: Pipeline
          name: good-morning-good-afternoon
        runAfter:
          - hello
        params:
          - name: a
            value: $(tasks.hello.results.message)
```
