### ISSUE TITLE
Add test to check bundle-location is correct

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/experimental#98]
# Expected Behavior
We should have a check that builds the bundle for our webhook extension code and then checks the resulting file matches is referenced in the bundle location for the extension service. Details below.

We have a config folder has `extension-service.yaml`, which specifies a bundle location. For example:

```
 annotations:
    tekton-dashboard-display-name: Webhooks
    tekton-dashboard-endpoints: "webhooks.web"
    tekton-dashboard-bundle-location: "web/extension.c2db219d.js"
```

When you do `npm run build`, you get a bundle created with a hash. 

We could simply do a grep on the extension service file and check it contains the hash representing our built code.

This check should be done as part of the tests that are run for every PR.

# Actual Behavior
We don't currently have such a check so developers can check in the wrong hash and therefore when attempting to install the extension just as a consumer, what's referenced in the service yaml what match what they've actually just built. 

Therefore the webhook extension will not be loaded.
