### ISSUE TITLE
[Pipeline in Pipeline] pipeline in pipeline controller does not work with Tekton git reolver 

### ISSUE THREAD

**Issue by TianxiangShen** [tektoncd/experimental#980]
### Feature request
I have following pipeline which is leveraging both git resolver and PIP controller. 
While it failed to start with error shown in the PIP controller:
 `{"level":"info","ts":1730933352.720542,"logger":"pip-controller.event-broadcaster","caller":"record/event.go:285","msg":"Event(v1.ObjectReference{Kind:\"CustomRun\", Namespace:\"yamaio-cd-dev\", Name:\"yamaio-test-child-pipeline-48e0f\", UID:\"b69d52f8-455e-4f22-aa1d-db62e51c1540\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"4631819032\", FieldPath:\"\"}): type: 'Warning' reason: 'InternalError' 1 error occurred:\n\t* run yamaio-cd-dev/yamaio-test-child-pipeline-48e0f is invalid because of missing field(s): name\n\n"}`
```
pipeline specs:
---
apiVersion: "tekton.dev/v1beta1"
kind: "Pipeline"
metadata:
  annotations: ...
  labels: ...
  name: "git-resolver-pip"
spec:
  params:
  - name: ...
    value: ...
  tasks:
  - name: "child-pipeline-48e0f"
    params:
    - name: ...
      value: ...
    taskRef:
      apiVersion: "tekton.dev/v1beta1"
      kind: "Pipeline"
      resolver: git
      params:
        - name: org
          value: qihuyang
        - name: repo
          value: demotestapp
        - name: revision
          value: master
        - name: pathInRepo
          value: src/main/resources/yamacontainer-7d0e66ea.yaml
```
```
status of CustomRun:
---
apiVersion: tekton.dev/v1beta1
kind: CustomRun
metadata:
...
status:
  completionTime: "2024-11-06T22:49:12Z"
  conditions:
  - lastTransitionTime: "2024-11-06T22:49:12Z"
    message: 'Run can''t be run because it has an invalid spec - missing field(s):
      name'
    reason: ReasonRunFailedValidation
    status: "False"
    type: Succeeded
```

### Use case

we've been using pipeline in pipeline feature a lot, since now we are trying to migrate all our pipelines/tasks to the github and leverage `git resolver` to fetch these pipelines/tasks, it will be really helpful that PIP created CustomRun can recognize the `git resolver`  field.
